config/routes.rb
AuraxisGoverned::Application.routes.draw do
  resources :characters

  resources :troopers

  resources :missions

  get "test/index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', as: :destroy_user_session
  end

  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      declare_mission(user)
    end
  end

  def declare_mission(user)
    can :read, Mission
    can :create, Mission
    can :manage, Trooper, mission: { id: user.mission_ids }
    can [:edit, :destroy], Mission, user: user
  end
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :troopers
  has_many :missions, through: :troopers

  before_create :get_game_id

  private

  def get_game_id
    self.character_id = PS.get_character_id_by_name(name)
  end
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  belongs_to :user

  has_many :troopers
  has_many :characters, through: :troopers

  validates :name, presence: true, length: { minimum: 3}
  validates :server, presence: true, length: { minimum: 3}
  validates :faction, presence: true, length: { minimum: 2}

  scope :free_to_join, -> { where(status: "Open") }

  def assign_trooper name
    character = Character.find_or_create_by name
    self.characters << character
    Rails.cache.delete("/mission/#{id}/troopers")
  end

  def troopers_data
    Rails.cache.fetch("/mission/#{id}/troopers", expires_in: 1.minute) do
      PS.get_characters_by_ids(self.characters.map(&:character_id))
    end
  end

  def to_s
    "#{name} (#{user.name})"
  end
end

app/models/ps.rb
module PS
  API_URL="http://census.soe.com/get/ps2:v2/"

  EXTRA_ITEMS=[
    "1", # Vehicle decoration
    "13", # Title
    "17", # camo
    "27", # Weapon attachment
    "28", # Boost
    "33", # Vehicle skill
    "36", # Class skill
    "38", # Vehicle decoration
    "39", # Character decoration
  ]

  class Character

    attr_reader :id, :name, :battle_rank, :aerospace, :infantry, :mechanized, :items, :online

    def initialize(opts={})
      @id = opts["character_id"]
      @name = opts["name"]["first"]
      @online = opts["online_status"] != "0"
      @battle_rank = opts["battle_rank"]["value"]
      @aerospace = opts["currency"]["aerospace"]
      @infantry = opts["currency"]["infantry"]
      @mechanized = opts["currency"]["mechanized"]
      @items = opts["items"].map{|i| Item.new(i)}.select{|i| !EXTRA_ITEMS.include?(i.type_id)}
    end
  end

  class Item

    attr_reader :id, :type_id, :name

    def initialize(opts={})
      @id = opts["item_id"]
      @type_id = opts["item_type_id"]
      @name = opts["name"]["en"] rescue "(unknown)"
    end
  end

  def self.get_character_id_by_name(name)
    response = HTTParty.get "#{API_URL}/character_name/?name.first_lower=#{name.downcase}&c:show=character_id"
    response.parsed_response["character_name_list"].first["character_id"]
  end

  def self.get_characters_by_name(names)
    get_characters_by_id get_character_ids_by_name(names)
  end

  def self.get_characters_by_ids(ids)
    response = HTTParty.get "#{API_URL}/character/?character_id=#{ids.join(",")}&c:resolve=currency,online_status,item_full"
    response.parsed_response["character_list"].map{|u| Character.new(u)}
  end

  def self.get_servers
    response = HTTParty.get "#{API_URL}/world/?c:limit=100"
    response.parsed_response["world_list"].map{|world| world["name"]["en"]}
  end

  def self.get_friends_of(ids)
    return [] if ids.empty?
    response = HTTParty.get "#{API_URL}/characters_friend/?character_id=#{ids.join(",")}&c:resolve=character_name"
    response.parsed_response["characters_friend_list"].map{|u| u["friend_list"].map{|f| f["name"]["first"] rescue nil}}.flatten.uniq.compact
  end
end

app/models/trooper.rb
class Trooper < ActiveRecord::Base
  belongs_to :mission
  belongs_to :character
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :omniauthable, omniauth_providers: [:steam]

  def self.find_for_steam_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.nickname
      #user.image = auth.info.image # assuming the user model has an image
      user.save!
    end
  end

  has_many :missions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  check_authorization unless: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    if current_user.nil?
      session[:next] = request.fullpath
      redirect_to login_url, alert: "You have to log in to continue."
    else
      if request.env["HTTP_REFERER"].present?
        redirect_to :back, alert: exception.message
      else
        redirect_to root_url, alert: exception.message
      end
    end
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  authorize_resource

  before_action :set_mission, only: [:show, :destroy]
  before_action :set_servers, only: [:new, :create]

  def show
    @trooper = @mission.troopers.new
    @friends = PS.get_friends_of(@mission.characters.map(&:character_id)) - @mission.characters.map(&:name)
  end

  def new
    @mission = Mission.new
  end

  def create
    @mission = current_user.missions.new(mission_params)

    respond_to do |format|
      if @mission.save
        format.html { redirect_to @mission, notice: 'Mission was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mission }
      else
        format.html { render action: 'new' }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    def set_servers
      @servers = PS.get_servers
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params.require(:mission).permit(:name, :status, :server, :faction)
    end
end

app/controllers/troopers_controller.rb
class TroopersController < ApplicationController

  authorize_resource

  def create
    trooper_params = params.require(:trooper).permit(:mission_id, character: [:name])
    mission = Mission.find trooper_params[:mission_id]
    mission.assign_trooper trooper_params[:character]
    redirect_to mission
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_filter :verify_authenticity_token
  def steam
    @user = User.find_for_steam_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Steam") if is_navigational_format?
    else
      session["devise.steam_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_authorization_check
  skip_before_filter :authenticate_user!

  def index
    @open_missions = Mission.free_to_join
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/troopers_helper.rb
module TroopersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Auraxis Governed
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #container
      %header
        %h1= link_to "Auraxis Governed", root_path
        %p PlanetSide 2 leader assistant tool.

      %nav
        - if user_signed_in?
          %p
            = current_user.name
            = link_to "Log out", destroy_user_session_path
        - else
          = link_to "Log in with Steam", user_omniauth_authorize_path(:steam)

      %section
        - flash.each do |name, msg|
          - if msg.is_a?(String)
            = content_tag :div, msg, class: "flash_#{name}"

        = yield

app/views/missions/_form.html.haml
= form_for @mission do |f|
  - if @mission.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mission.errors.count, "error")} prohibited this mission from being saved:"
      %ul
        - @mission.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :server
    = f.select :server, @servers
  .field
    = f.label :faction
    = f.select :faction, ["VS", "NC", "TR"]
  .actions
    = f.submit 'Save'

app/views/missions/new.html.haml
%h1 New mission

= render 'form'

app/views/missions/show.html.haml
%h2= @mission.name

%p
  = @mission.status
  mission by
  = @mission.user.name

%p
  %b Server:
  = @mission.server
%p
  %b Faction:
  = @mission.faction

%h3 Troopers

- if @mission.characters.empty?
  %p No troopers yet
- else
  %table
    %thead
      %tr
        %th Name
        %th BR
        %th Online
        %th Resources
    %tbody
      - @mission.troopers_data.each do |character|
        %tr
          %td= character.name
          %td= character.battle_rank
          %td= character.online
          %td A:#{character.aerospace}|M:#{character.mechanized}|I:#{character.infantry}

= form_for @trooper do |f|
  = f.hidden_field :mission_id
  = f.fields_for :character do |c|
    .field
      = c.label :name
      = c.text_field :name
  .actions
    = f.submit 'Save'

- unless @friends.empty?
  %h4 Add friends of current troopers?

  %p
    - @friends.each do |friend|
      %span= friend

- if can?(:destroy, @mission)
  %p= link_to 'Cancel this mission', @mission, method: :delete, data: { confirm: 'Are you sure?' }

app/views/welcome/index.html.haml
%h1 Missions
%h2 Open missions

- unless @open_missions.empty?
  %ul
    - @open_missions.each do |mission|
      %li= link_to mission, mission
- else
  %p Currently no open missions...

- if user_signed_in?
  %h2 My missions
  %ul
    - current_user.missions.each do |mission|
      %li= link_to mission, mission

  %p= link_to "Create new mission", new_mission_path